### ISSUE TITLE
Sign the assemblies. 

### ISSUE THREAD

**Issue by Uolifry** [IgniaAustralia/SPMeta2.NintexExt#8]
Could you please sing the assemblies, as it's not possible to use it on projects where we have assemblies sing?

You could use the same key as it on official spmeta2 repo https://github.com/SubPointSolutions/spmeta2/blob/master/SPMeta2.snk 
or create a new one. 

Thanks.

**Comment by maratbakirov** [comment]
Fixed in release df7f3ef6951445da630e6469feeb1d6792c64122

**Comment by maratbakirov** [comment]
0.0.7 versions of both assemblies published into nuget.
