### ISSUE TITLE
Workflow delivery doesn't work for Kerberos authentication - on-prem.

### ISSUE THREAD

**Issue by Uolifry** [IgniaAustralia/SPMeta2.NintexExt#9]
Workflow delivery doesn't work on-prem if SP servicer configured to work with for Kerberos authentication.

**Comment by maratbakirov** [comment]
for future reference ... 
https://pastebin.com/m51QqqHc

**Comment by maratbakirov** [comment]
code sampel provided 
https://pastebin.com/m51QqqHc

**Comment by maratbakirov** [comment]
fixed in V0.0.8
